### PR TITLE
Introducing Custom bbcodes

### PR DESCRIPTION
**Pull request by vinny**
Issue 32 - Support for custom BBCodes

### CODE REVIEW

**Comment by michaelcullum** [comment]
```
[phpBB Debug] PHP Notice: in file [ROOT]/includes/mods/functions_blog.php on line 540: Undefined variable: user
[phpBB Debug] PHP Notice: in file [ROOT]/includes/mods/functions_blog.php on line 540: Trying to get property of non-object
```

I get this debug and it doesn't parse the custom bbcodes, it just shows them on the posting page

**Comment by michaelcullum** [comment]
Actually I don't think the debug was you, that was david. But still it doesn't parse.

**Comment by vinny** [comment]
Very weird. -.-'
I tested and works fine to create/edit articles. 

Display correctly in the post and parse perfectly when viewing the home blog and article page.

**Comment by vinny** [comment]
This error is caused by https://github.com/phpBB-Blog/phpBB-Blog/pull/31

If the line:
<code>// Assigning custom bbcodes
display_custom_bbcodes();</code>
is removed, the error continues.

@edit
Fix:
Open <code>includes/mods/functions_blog.php</code>
Find: <code>global $db, $template, $config;</code>
Replace with: <code>global $db, $user, $template, $config;</code>

**Comment by imkingdavid** [comment]
What line is that around? Have you made sure you're on the latest commit? I cannot find that exact find at the moment.

**Comment by vinny** [comment]
line 483. 

the same: https://github.com/phpBB-Blog/phpBB-Blog/pull/40

**Comment by imkingdavid** [comment]
Ahh, well that's already fixed then.

**Comment by michaelcullum** [comment]
I just fixed it. ;)

**Pull request merged**
